name: Test

on: [push, pull_request]


jobs:
  test:
    environment: Test
    env:
      EMAIL: ${{ vars.EMAIL }}
      SERVER: ${{ vars.SERVER }}
      TOKEN: ${{ secrets.TOKEN }}
      PASSWORD: ${{ secrets.PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1'
      - name: Test
        run: make test